# Generated by Django 2.1.3 on 2018-12-03 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='hotel',
            name='contact',
            field=models.OneToOneField(default=type, on_delete=django.db.models.deletion.CASCADE, to='web.Contact'),
            preserve_default=False,
        ),
    ]
