# Generated by Django 2.1.3 on 2018-12-04 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20181203_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.Hotel')),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.Room')),
            ],
        ),
    ]
