# Generated by Django 2.1.3 on 2018-12-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20181204_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(default=' ', max_length=12),
        ),
    ]
