# Generated by Django 2.1.3 on 2018-12-04 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20181204_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilities',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='roomlink',
            name='Hotel',
        ),
        migrations.RemoveField(
            model_name='roomlink',
            name='Room',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Facilities',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomLink',
        ),
    ]
