# Generated by Django 2.1.3 on 2018-12-04 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20181204_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomlink',
            name='Hotel',
        ),
        migrations.RemoveField(
            model_name='roomlink',
            name='Room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
        migrations.AddField(
            model_name='hotel',
            name='room',
            field=models.ForeignKey(default='Change this', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='web.Room'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RoomLink',
        ),
    ]
